### ISSUE TITLE
Animations are not preserved when exporting

### ISSUE THREAD

**Issue by Fox-Int** [Saalvage/AssimpNetter#13]
When exporting an fbx file the animations aren't included. 

As an example here is a quick console app which basically imports an fbx file and then exports the file.
`using Assimp;

namespace AssimpProcessor
{
    class Program
    {
        static void Main(string[] args)
        {
            if (args.Length < 2)
            {
                Console.WriteLine("Usage: AssimpProcessor <input-file-path> <output-directory>");
                return;
            }

            string inputFile = args[0];
            string outputDirectory = args[1];

            // Ensure the output directory exists
            if (!Directory.Exists(outputDirectory))
            {
                Console.WriteLine($"Creating output directory: {outputDirectory}");
                Directory.CreateDirectory(outputDirectory);
            }

            // Create the output file path
            string outputFile = Path.Combine(
                outputDirectory,
                $"{Path.GetFileNameWithoutExtension(inputFile)}_processed{Path.GetExtension(inputFile)}"
            );

            try
            {
                Console.WriteLine($"Processing file: {inputFile}");
                Console.WriteLine($"Output will be saved to: {outputFile}");
                
                var context = new AssimpContext();
                context.SetConfig(new Assimp.Configs.FBXPreservePivotsConfig(false));
                //Import the file with preprocessing
                var scene = context.ImportFile(inputFile,
                    PostProcessSteps.Triangulate |
                    PostProcessSteps.GenerateNormals |
                    PostProcessSteps.ValidateDataStructure );

                //Export the processed file
                context.ExportFile(scene, outputFile, "fbx");
                Console.WriteLine($"File processed successfully: {outputFile}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error processing file: {ex.Message}");
            }
        }
    }
}
`

You can use it like so in cmd:
`AssimpProcessor.exe "C:\path\to\input.fbx" "C:\path\to\output\directory"`

Here are 2 fbx files with animations: 
[C4D FBX](https://www.dropbox.com/scl/fi/cx35seolwafg7j21oxpy5/Walking_C4D.fbx?rlkey=k2hrdv6gxxzg62opqqftjbe8m&st=ry5dw42t&dl=0)
[Mixamo FBX](https://www.dropbox.com/scl/fi/l3qj6sjwuqkpza1htte59/Walking_Mixamo.fbx?rlkey=ttw1vtwyuplzfm7uxlup2rjzo&st=k37to7dy&dl=0)

One was downloaded directly from Mixamo and the other is the same model but imported and exported from Cinema 4d.

Additional strange behavior: the line "context.SetConfig(new Assimp.Configs.FBXPreservePivotsConfig(false));"
If this is set to true when importing the Mixamo file the app will crash.

**Comment by Saalvage** [comment]
Just to make sure this isn't an upstream issue, could you check whether the issue also occurs with the following piece of code:

```cs
//Import the file with preprocessing
var scene = AssimpLibrary.Instance.ImportFile(inputFile,
    PostProcessSteps.Triangulate |
    PostProcessSteps.GenerateNormals |
    PostProcessSteps.ValidateDataStructure, 0);

//Export the processed file
AssimpLibrary.Instance.ExportScene(scene, "fbx", outputFile, 0, 0);
```

This produces binary-identical output to unwrapped (C/C++) Assimp, so if the issue persists it'd be an issue with Assimp itself, if not then it's an issue with the marshalling to/from a scene which I'll need to fix.

The issue with the config I will investigate further once this has been resolved.
Thank you for your report!

**Comment by Fox-Int** [comment]
Hi, Thanks for getting back to me.
I think its possibly an Assimp issue as I get the same problem with your code as well. 

As an extra test I checked the FileLoadDemo in HelixToolKit.SharpDX which uses the older AssimpNet and I get the same issue too.

**Comment by Saalvage** [comment]
Adding console logging via `new ConsoleLogStream().Attach();` we can see the following message:
`Warn,  T30220: FBX-DOM: unsupported, newer format version, supported are only FBX 2011, FBX 2012 and FBX 2013, trying to read it nevertheless`.

This may be the cause of our issues. FBX is a proprietary format owned by Autodesk, which is probably related to its subpar support. If possible I would try using a different format if your use case allows for that.
FBX exporting is also considered experimental as per https://github.com/assimp/assimp/blob/master/doc/Fileformats.md.

Reimporting `outputFile` after exporting it first also logs a ton of errors relating to animation.

I would recommend potentially opening an upstream issue about this, I don't think there's much I can do on the wrapper's end.
I've also tested the `context.SetConfig(new Assimp.Configs.FBXPreservePivotsConfig(true));` and could not reproduce your crashing. `true` is also the default value for this property.

**Comment by Fox-Int** [comment]
Hi, yeah ive gone through most of this.
I have exported different fbx versions and tested:
Walking_C4D_2012, Walking_C4D_2013, Walking_C4D_2014-15, Walking_C4D_2016-17-18.
Still I get the animation issue.

in regards to the FBXPreservePivotsConfig issue. I had a bit of a mix up. This is actually an issue with AssimpNet and not AssimpNetter.

So for the app I'm creating I wanted to support the maximum number of FBX versions.
The app uses HelixToolKit but unfortunately it uses a slightly outdated AssimpNet which is causing me some problems.
So the code a posted originally was to use AssimpNetter to automatically import and export the fbx files so they can be used with HelixToolKits AssimpNet which kind of works in that im able to import the models without any crashes... But i get the issue with animations. I'm kind of at a loss with how to proceed at the moment.

**Comment by Fox-Int** [comment]
I did actually have a play with using AssimpNetter in place of AssimpNet in HelixToolKit but it didnt fix the issue with animations.
I'll continue to have a play and see what I can figure out.

I was thinking of maybe trying to use a different format but i really would rather fbx. obj doesn't support bones or animations so thats a no go. I could go with gltf as its compatible in both Godot and Unity. 

I guess ill see how things go. Thanks

**Comment by Saalvage** [comment]
Do you think there's anything left that could be done here on the wrapper? If not this issue should be closed. Feel free to reach out if you have any more questions though!

**Comment by Fox-Int** [comment]
Erm I dont think so. I've confirmed it's an issue with Assimp it's self by using the Assimp Viewer [Here](https://kimkulling.itch.io/the-asset-importer-lib) which uses Assimp 5.4.3. I've raised a bug over there so hopefully it will eventually get fixed.

**Comment by Saalvage** [comment]
Alright, thanks! For future reference: https://github.com/assimp/assimp/issues/5909
