### ISSUE TITLE
How to build assimp.dll from Assimp sources

### ISSUE THREAD

**Issue by neoxeo** [Saalvage/AssimpNetter#14]
Hi,

Thanks a lot for your fantastic job !

Can you tell me how to build assimp.dll present into /AssimpNetter/tree/master/libs/win-x64 from assimp repository ?

I try to build it with this : 
https://github.com/assimp/assimp/blob/master/Build.md and vcpkg method or Visual Studio method

but it create assimp-vc143-mt.dll not assimp.dll.  

Thanks again.

**Comment by Saalvage** [comment]
That's normal, Visual Studio adds vc143 (specifying the Visual C++ toolset version) and mt (specifying the release config) to the DLL's name, you can just rename the file manually.

**Comment by neoxeo** [comment]
Thanks a lot for this quick and complete answer.

It is so simple that I haven't test this.

Thanks again and congratulations for your AssimpNetter !!!

**Comment by Saalvage** [comment]
I assume this means I can resolve this issue. If you have any further questions feel free to open a new issue! Thank you! :)

**Comment by neoxeo** [comment]
Issue resolved, I confirm. I rename file to assimp.dll and it works fine !
